### ISSUE TITLE
Interested in collaborating 

### ISSUE THREAD

**Issue by rohanmech** [Nit-nit/hazy#2]
well nvm

**Comment by Nit-nit** [comment]
Oh, well my 3 year old nephew broke my phone a week ago, today I signed in to my account using my mom's mobile lmao

**Comment by Nit-nit** [comment]
Yooo Rohan, I appreciated that you showed some interest in my repository, thanks for that, but I will be offline for next two months, I will barely come online :(
I am looking for collaborating without too soon, but I'm just a noob who doesn't know how to write a single code snippet correctly

**Comment by Nit-nit** [comment]
And yo thank for your GitHub username, I will surely friend you there as soon as I sign in to my account, because I have 2 step auth on, I cannot get the auth code to sign in

**Comment by Nit-nit** [comment]
![IMG_20220719_064143](https://user-images.githubusercontent.com/94877880/179642619-85f5a4d6-78b2-4520-b15c-15573b72a64e.jpg)
Oh shoot!!

**Comment by Nit-nit** [comment]
I added you as a collaborator good friend 😎👍
We will discuss what functions should we add later
Until then you are allowed to mess around and add functions you feel like lol

**Comment by Nit-nit** [comment]
Sorry if you felt hurt btw 😭😭

**Comment by rohanmech** [comment]
> Oh, well my 3 year old nephew broke my phone a week ago...

I had no idea that you went through such mishap. I closed the thread just after 3 days thinking I'm prolly being presumptuous.

> I am looking for collaborating with you too soon, but I'm just a noob who doesn't know how to write a single code snippet correctly

Well, I'm not a pro either. Coding is a cumulative process that builds our proficiency day after day and collaboration is a great way of fast paced learning. No worries if you're busy at the moment. Just keep on honing your skill and let me know if you ever need help with something. Even if it's something totally unfamiliar to me I can always learn and get back to aid you.

> I added you as a collaborator...

I just accepted the invitation but I won't be touching it until you're free again.

**Comment by Nit-nit** [comment]
> I accepted the invitation...
Are you sure about this? Because my my phone says there is only 1 contributor, and that's me.

**Comment by rohanmech** [comment]
@Nit-nit I'm sure that I'm added as a contributor because I options like create new release, or publish a package options are accessible to me. But I'm not sure why you aren't able to see me as a contributor. Pyolly because I haven't made any contributions? idk...

**Comment by rohanmech** [comment]
Well well...

![Screenshot_20220722-005714_GitHub.jpg](https://user-images.githubusercontent.com/56753450/180299487-8d6f03bb-1f3d-4906-89e3-902792511d0b.jpg)

**Comment by Nit-nit** [comment]
I guess we should close this issues now? Because I gladly accept you as a contributor and I'm looking forward to get good help from you lmao.

**Comment by rohanmech** [comment]
Sure! Sounds good. I'm closing this issue. And feel free to reach out to me on discord when you’ve logged into your account on discord. My username: Rohanmech#0105
